name: NoHorseFallDamage
author: Strahan
main: com.sylvcraft.NoHorseFallDamage
version: 1.1
api-version: 1.15
description: The title says it all
commands:
  horsefall:
    description: Plugin command
